"""Tipos de dominio: Span, GoldenItem, EvalResult, Diagnosis, GateVerdict, RunRecord, Report."""

from ratchet.domain.enums import (
    TERMINAL_STATES,
    ApprovalDecision,
    ApprovalKind,
    Capa,
    EvalStatus,
    FixLayer,
    GateDecision,
    MonitorSource,
    ReportDecision,
    Role,
    RunState,
    RunStatus,
)
from ratchet.domain.errors import RagError
from ratchet.domain.models import (
    ApprovalRequest,
    Baseline,
    Chunk,
    ChunkBoundaryInfo,
    Diagnosis,
    Document,
    EvalResult,
    GateVerdict,
    GoldenItem,
    GoldenSet,
    MonitorSignal,
    Operator,
    Patch,
    PatchHandle,
    PerItemResult,
    ProbeResults,
    Report,
    RunRecord,
    Span,
    StateRef,
    Writeup,
)

__all__ = [
    "ApprovalDecision",
    "ApprovalKind",
    "Capa",
    "EvalStatus",
    "FixLayer",
    "GateDecision",
    "MonitorSource",
    "ReportDecision",
    "Role",
    "RunStatus",
    "RunState",
    "TERMINAL_STATES",
    "RagError",
    "Span",
    "Chunk",
    "Document",
    "StateRef",
    "PerItemResult",
    "EvalResult",
    "ChunkBoundaryInfo",
    "ProbeResults",
    "Diagnosis",
    "GateVerdict",
    "MonitorSignal",
    "Report",
    "GoldenItem",
    "GoldenSet",
    "Baseline",
    "Writeup",
    "Patch",
    "PatchHandle",
    "ApprovalRequest",
    "Operator",
    "RunRecord",
]
